format = """
[┏━](bold color_delim) \
$os\
$username\
[┃](bold color_delim)\
$directory\
$fill \
$git_branch $git_status $git_state\
$python\
$rust\
$c\
$docker_context\
[ ━┓](bold color_delim)
[┗━❯ ](bold color_delim) \
"""

palette = 'blue'

[palettes.blue]
color_delim = '#3399FF'
color_fill = 'black'


[fill]
symbol = "-"
style = "bold color_fill"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:none"
style_root = "bg:none"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = "[$symbol ]($style)"
style = "white"
disabled = false      # Disabled by default

[os.symbols]
Macos = ""
Windows = ""
Ubuntu = ""
Fedora = ""

[directory]
style = "bg:none"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~" = ""
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bold green"
format = '[$symbol $branch]($style)'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '[+\($count\)](green)'
untracked = '[?$count](blue)'

format = '[$all_status]($style)'

[git_state]
format = '[$state]($style)'
disabled = false

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'


[python]
symbol = ""
version_format = "v${major}.${minor}"
style = "yellow bold"
format = "[$symbol${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'
